<template>
	<EdgeAppShell product="eduedge" title="EduEdge" :tenant-name="data.selected_branch?.institution_name || ''" :branch-name="data.selected_branch?.branch_name || 'Instructors'" :menu-items="menuItems" active-route="/app/eduedge-instructors" @navigate="openRoute">
		<EdgePageLayout>
			<template #header><EdgePageHeader eyebrow="People Operations" title="Instructors" subtitle="Maintain instructor identity, qualifications, specialisation and operational Branch eligibility." :action-label="canCreate ? 'Add Instructor' : ''" @action="newInstructor" /></template>
			<EdgeLoadingState v-if="loading && !loaded" message="Loading instructors..." :skeleton="true" />
			<EdgeErrorState v-else-if="error && !loaded" title="Instructors could not load" :message="error" action-label="Try again" @retry="load" />
			<template v-else>
				<EdgeFilterBar title="Instructor filters"><div class="people-filters"><label><span>Branch / Campus</span><select v-model="filters.branch" class="form-control" @change="branchChanged"><option v-for="row in data.allowed_branches" :key="row.name" :value="row.name">{{ row.branch_name || row.name }}</option></select></label><label><span>Search</span><input v-model.trim="filters.search" class="form-control" placeholder="Instructor name or ID" @keyup.enter="load(true)" /></label></div><template #actions><button type="button" class="edge-button edge-button--primary" @click="load(true)">Apply</button></template></EdgeFilterBar>
				<p v-if="error" class="people-error">{{ error }}</p>
				<section class="people-layout">
					<article class="people-panel">
						<div class="people-heading"><div><p class="edge-eyebrow">Staff register</p><h2>Instructors</h2></div><button v-if="canCreate" type="button" class="edge-button" @click="newInstructor">Add Instructor</button></div>
						<EdgeEmptyState v-if="!loading && !data.instructors.length" title="No instructors found" description="Add an Instructor profile for this Branch." />
						<div v-else class="people-list"><button v-for="row in data.instructors" :key="row.name" type="button" class="person-card" :class="{ 'is-selected': draft.name === row.name }" @click="editInstructor(row.name)"><div class="avatar"><img v-if="row.image" :src="row.image" :alt="row.instructor_name" /><span v-else>{{ initials(row.instructor_name) }}</span></div><span><strong>{{ row.instructor_name || row.name }}</strong><small>{{ row.department || 'No department' }} · {{ row.eduedge_mobile || row.eduedge_email || row.name }}</small></span><EdgeStatusBadge :label="row.status || 'Active'" :status="row.status || 'active'" :tone="row.status === 'Left' ? 'danger' : 'success'" /></button></div>
						<div class="paging"><button type="button" class="edge-button" :disabled="data.paging.start <= 0" @click="previousPage">Previous</button><span>{{ data.paging.start + (data.instructors.length ? 1 : 0) }}–{{ data.paging.start + data.instructors.length }}</span><button type="button" class="edge-button" :disabled="!data.paging.has_more" @click="nextPage">Next</button></div>
					</article>
					<article class="people-panel editor">
						<div class="people-heading"><div><p class="edge-eyebrow">Official instructor profile</p><h2>{{ draft.name ? draft.instructor_name || draft.name : 'New Instructor' }}</h2></div><div class="actions"><button v-if="draft.name" type="button" class="edge-button" @click="openAssignments">Instructor Assignments</button><button v-if="draft.name" type="button" class="edge-button" @click="openFullForm">Open full form</button><button type="button" class="edge-button edge-button--primary" :disabled="saving || !canSave" @click="save">{{ saving ? 'Saving...' : 'Save instructor' }}</button></div></div>
						<div class="profile-summary"><div class="photo"><img v-if="draft.image" :src="draft.image" :alt="draft.instructor_name || 'Instructor photo'" /><span v-else>{{ initials(draft.instructor_name) }}</span></div><div><strong>Instructor photograph</strong><small>Used on staff identity and teaching records.</small></div><button v-if="draft.name && canEdit" type="button" class="edge-button" @click="uploadPhoto">Upload / replace</button></div>
						<div class="people-grid">
							<label><span>Instructor name *</span><input v-model.trim="draft.instructor_name" class="form-control" :disabled="!canEdit" /></label>
							<label><span>Status</span><select v-model="draft.status" class="form-control" :disabled="!canEdit"><option>Active</option><option>Left</option></select></label>
							<label><span>Primary Branch / Campus *</span><select v-model="draft.eduedge_primary_branch" class="form-control" :disabled="!canEdit"><option v-for="row in data.allowed_branches" :key="row.name" :value="row.name">{{ row.branch_name || row.name }}</option></select></label>
							<label><span>Department / School Section</span><select v-model="draft.department" class="form-control" :disabled="!canEdit"><option value="">Not assigned</option><option v-for="row in data.departments" :key="row.name" :value="row.name">{{ row.department_name || row.name }}</option></select></label>
							<label><span>Linked Employee</span><select v-model="draft.employee" class="form-control" :disabled="!canEdit"><option value="">No Employee link</option><option v-for="row in data.employees" :key="row.name" :value="row.name">{{ row.employee_name || row.name }}</option></select></label>
							<label><span>Gender</span><select v-model="draft.gender" class="form-control" :disabled="!canEdit"><option value="">Not specified</option><option v-for="row in data.genders" :key="row.name" :value="row.name">{{ row.name }}</option></select></label>
							<label><span>Email</span><input v-model.trim="draft.eduedge_email" type="email" class="form-control" :disabled="!canEdit" /></label>
							<label><span>Mobile number</span><input v-model.trim="draft.eduedge_mobile" class="form-control" :disabled="!canEdit" /></label>
							<label><span>Employment type</span><select v-model="draft.eduedge_employment_type" class="form-control" :disabled="!canEdit"><option value="">Not specified</option><option>Full-Time</option><option>Part-Time</option><option>Contract</option><option>Visiting</option><option>Volunteer</option></select></label>
							<label class="wide"><span>Qualification</span><textarea v-model.trim="draft.eduedge_qualification" class="form-control" rows="2" :disabled="!canEdit"></textarea></label>
							<label class="wide"><span>Specialisation</span><textarea v-model.trim="draft.eduedge_specialisation" class="form-control" rows="2" :disabled="!canEdit"></textarea></label>
						</div>
						<template v-if="draft.name"><h3>Current academic assignments</h3><EdgeEmptyState v-if="!draft.assignments?.length" title="No Instructor Assignment" description="Assign this Instructor to a Programme Offering, Class Arm and Course." /><div v-else class="assignment-list"><article v-for="row in draft.assignments" :key="row.name"><strong>{{ row.assignment_title || row.assignment_type }}</strong><small>{{ row.student_group }} · {{ row.course || 'Whole class' }} · {{ row.enabled ? 'Active' : 'Disabled' }}</small></article></div></template>
						<p v-if="saveError" class="people-error">{{ saveError }}</p>
					</article>
				</section>
			</template>
		</EdgePageLayout>
	</EdgeAppShell>
</template>

<script>
import { EDUEDGE_MENU_ITEMS, openEduEdgeRoute } from "../eduedge_ui/navigation";
const blankInstructor = (branch = "") => ({ name: "", instructor_name: "", employee: "", gender: "", status: "Active", department: "", eduedge_institution: "", eduedge_primary_branch: branch, eduedge_email: "", eduedge_mobile: "", eduedge_qualification: "", eduedge_specialisation: "", eduedge_employment_type: "", image: "", assignments: [] });
const blankData = () => ({ allowed_branches: [], selected_branch: {}, instructors: [], instructor: null, departments: [], employees: [], genders: [], permissions: {}, paging: { start: 0, page_length: 25, has_more: false } });
export default {
	name: "EduEdgeInstructors",
	data() { return { menuItems: EDUEDGE_MENU_ITEMS, loading: true, loaded: false, saving: false, error: "", saveError: "", filters: { branch: "", search: "", start: 0 }, data: blankData(), draft: blankInstructor() }; },
	computed: { canCreate() { return Boolean(this.data.permissions?.can_create); }, canEdit() { return this.draft.name ? Boolean(this.data.permissions?.can_write) : this.canCreate; }, canSave() { return Boolean(this.canEdit && this.draft.instructor_name && this.draft.eduedge_primary_branch); } },
	mounted() { this.load(); },
	methods: {
		openRoute: openEduEdgeRoute,
		initials(value) { return String(value || "I").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); },
		async load(reset = false, instructor = "") { if (reset) this.filters.start = 0; this.loading = true; this.error = ""; try { const response = await frappe.call("eduedge.api.people_operations.get_instructors_page", { branch: this.filters.branch || undefined, search: this.filters.search || undefined, instructor: instructor || undefined, start: this.filters.start, page_length: this.data.paging.page_length || 25 }); this.data = response.message || blankData(); this.filters.branch = this.data.selected_branch?.name || this.filters.branch; this.loaded = true; if (instructor && this.data.instructor) this.draft = { ...blankInstructor(this.filters.branch), ...this.data.instructor }; else if (!this.draft.name) this.draft.eduedge_primary_branch = this.filters.branch; } catch (error) { this.error = error?.message || "Instructors could not be loaded."; } finally { this.loading = false; } },
		branchChanged() { this.draft = blankInstructor(this.filters.branch); this.load(true); }, newInstructor() { this.draft = blankInstructor(this.filters.branch); this.saveError = ""; }, editInstructor(name) { this.load(false, name); },
		async save() { if (!this.canSave) return; this.saving = true; this.saveError = ""; try { const response = await frappe.call("eduedge.api.people_operations.save_instructor", { payload: JSON.stringify(this.draft) }); this.draft = { ...blankInstructor(this.filters.branch), ...(response.message || {}) }; frappe.show_alert({ message: __("Instructor saved"), indicator: "green" }); await this.load(true, this.draft.name); } catch (error) { this.saveError = error?.message || "Instructor could not be saved."; } finally { this.saving = false; } },
		uploadPhoto() { if (!this.draft.name || !frappe.ui?.FileUploader) return; new frappe.ui.FileUploader({ doctype: "Instructor", docname: this.draft.name, fieldname: "image", allow_multiple: false, is_private: 1, restrictions: { allowed_file_types: ["image/*"], max_file_size: 2 * 1024 * 1024 }, on_success: async (file) => { try { const response = await frappe.call("eduedge.api.people_operations.set_instructor_photo", { instructor: this.draft.name, file_url: file.file_url }); this.draft = { ...this.draft, ...(response.message || {}) }; frappe.show_alert({ message: __("Instructor photo updated"), indicator: "green" }); } catch (error) { this.saveError = error?.message || "Instructor photo could not be saved."; } } }); },
		openAssignments() { window.location.href = `/app/eduedge-instructor-assignments?branch=${encodeURIComponent(this.filters.branch)}&instructor=${encodeURIComponent(this.draft.name)}`; }, openFullForm() { window.open(`/app/instructor/${encodeURIComponent(this.draft.name)}`, "_blank", "noopener,noreferrer"); },
		previousPage() { this.filters.start = Math.max(0, this.filters.start - this.data.paging.page_length); this.load(); }, nextPage() { this.filters.start += this.data.paging.page_length; this.load(); },
	},
};
</script>

<style scoped>
.people-filters,.people-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:.75rem; width:100%; }.people-filters label,.people-grid label { display:grid; gap:.35rem; font-weight:600; }.people-layout { display:grid; grid-template-columns:minmax(18rem,.75fr) minmax(0,1.5fr); gap:1rem; margin-top:1rem; }.people-panel { display:grid; gap:1rem; align-content:start; padding:1rem; border:1px solid var(--border-color); border-radius:12px; background:var(--card-bg); }.people-heading,.actions,.profile-summary { display:flex; align-items:center; justify-content:space-between; gap:.75rem; flex-wrap:wrap; }.people-heading h2,.people-panel h3 { margin:0; }.people-list,.assignment-list { display:grid; gap:.65rem; }.person-card { display:grid; grid-template-columns:auto minmax(0,1fr) auto; align-items:center; gap:.75rem; padding:.75rem; border:1px solid var(--border-color); border-radius:8px; background:var(--control-bg); text-align:left; }.person-card:hover,.person-card.is-selected { border-color:var(--primary); }.person-card span,.assignment-list article { display:grid; gap:.15rem; }.person-card small,.assignment-list small,.profile-summary small { color:var(--text-muted); }.avatar,.photo { display:grid; place-items:center; overflow:hidden; border-radius:50%; border:1px solid var(--border-color); background:var(--card-bg); font-weight:700; }.avatar { width:2.8rem; height:2.8rem; }.photo { width:7rem; height:7rem; font-size:2rem; }.avatar img,.photo img { width:100%; height:100%; object-fit:cover; }.profile-summary { justify-content:flex-start; padding:1rem; border-radius:8px; background:var(--control-bg); }.profile-summary > div:nth-child(2) { display:grid; gap:.25rem; flex:1; }.people-grid .wide { grid-column:1/-1; }.assignment-list article { padding:.7rem; border:1px solid var(--border-color); border-radius:8px; background:var(--control-bg); }.paging { display:flex; justify-content:space-between; align-items:center; }.people-error { color:var(--red-600,#b42318); } @media (max-width:1000px) { .people-layout { grid-template-columns:1fr; } } @media (max-width:680px) { .people-filters,.people-grid { grid-template-columns:1fr; }.people-grid .wide { grid-column:auto; }.person-card { grid-template-columns:auto 1fr; }.person-card > :last-child { grid-column:1/-1; } }
</style>
